#!/bin/bash

BAT=/sys/class/power_supply/BAT0

while true; do
    now=$(<"$BAT/charge_now")
    cap=$(<"$BAT/charge_full")
    battery=$(( 100 * now / cap))
    batstat=$(cat "$BAT/status")

    date=$(date '+%Y-%m-%d %X')

    echo " ${batstat}, ${battery}% | ${date}"
    sleep 5
done
