[window]
padding.x = 16
padding.y = 12
decorations = "none"
startup_mode = "fullscreen"
option_as_alt = "Both"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[font]
size = 16

[font.normal]
family = "CommitMono"
style = "Regular"

[font.bold]
family = "CommitMono"
style = "Bold"

[font.italic]
family = "CommitMono"
style = "Italic"

[scrolling]
history = 10000

[general]
import = ["~/.config/alacritty/ashen.toml"]

[[keyboard.bindings]]
key = "F1"
command = {program = "brightnessctl", args = ["set", "5%-"]}
[[keyboard.bindings]]
key = "F2"
command = {program = "brightnessctl", args = ["set", "5%+"]}
