#!/usr/bin/env zsh

export EDITOR=kak
export VISUAL=kak

HISTFILE="$HOME/.cache/zsh/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY

autoload -Uz compinit
compinit -d "$HOME/.cache/zsh/zcompdump"
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' menu select

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats '[%b] '
precmd() { vcs_info }
setopt PROMPT_SUBST

PROMPT='%~ %F{242}${vcs_info_msg_0_}%f: '

bindkey -v
bindkey -M viins '^?' backward-delete-char
export KEYTIMEOUT=1

export EZA_CONFIG_DIR="$HOME/.config/eza/"

source "$HOME/.config/shell/aliases.sh" 

eval "$(zoxide init zsh --cmd cd)"
