source "%val{config}/plugins/lsp.kak"
# set global lsp_debug true
source "%val{config}/plugins/buffers.kak"
source "%val{config}/utils/clipboard.kak"
source "%val{config}/utils/pickers.kak"
source "%val{config}/utils/tmux.kak"
source "%val{config}/utils/numbers.kak"
source "%val{config}/languages/markdown.kak"
source "%val{config}/languages/c.kak"
source "%val{config}/languages/python.kak"

# --- appearance ---
colorscheme ashen
set-option global ashen_dynamic_cursor true
set-option global startup_info_version 99999999
set-option global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}}'
# add-highlighter global/ruler  column -ruler │ 81 %opt{g_9}

# --- editing ---
# set-option global autocomplete prompt
set-option global completers

set-option global scrolloff 8,4

set-option global aligntab false
set-option global indentwidth 4

hook global InsertChar '\t' %{ execute-keys -draft "h%opt{indentwidth}@" }
hook global InsertDelete ' ' %{ try %sh{
    printf "%s\n" 'execute-keys -draft -itersel "<a-h><a-k>^\h+.\z<ret>I<space><esc><lt>"'
} catch %{ try %{
    execute-keys -itersel -draft "h%opt{softtabstop}<s-h>2<s-l>s\h+\z<ret>d"
}}}

set-option global disabled_hooks .*-insert

# --- maps ---
map global normal <esc> ";,"
map global normal <ret> ":w<ret>"
map global normal '#'   ":comment-line<ret>"
map global normal j     "gd"
map global normal k     "gu"
map global normal J     "Gd"
map global normal K     "Gu"
map global normal <tab> "<esc>:bn<ret>" -docstring "next buffer"

map global user f   ":file-picker-prompt<ret>" -docstring "file picker"
map global user =   ":split<ret>"             -docstring "vertical split"
map global user '\' ":vsplit<ret>"             -docstring "horizontal split"
map global user t   ":tabnew<ret>"             -docstring "new tab"

