source "%val{config}/plugins/lsp.kak"
source "%val{config}/plugins/buffers.kak"
# TODO: read through jump
source "%val{config}/plugins/jump.kak"

source "%val{config}/utils/clipboard.kak"
source "%val{config}/utils/windowing.kak"
# TODO: helix inspired match mode

evaluate-commands %sh{
    for file in $kak_config/filetypes/*.kak; do
        printf 'source %s\n' "$file"
    done
}

# ======== appearance ========

colorscheme ashen
set-option global startup_info_version 99999999
set-option -add global modelinefmt \
    '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}}'
set-option global ui_options terminal_assistant=none

hook global WinCreate .* %{
    add-highlighter window/ruler column -ruler │ 81 %opt{g_9}
    add-highlighter window/line-numbers number-lines -relative -hlcursor -separator ""
}

# ======== editing ========

hook global InsertCompletionShow .* %{
    map global insert <tab> <c-n>
    map global insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
    unmap global insert <tab>
    unmap global insert <s-tab>
}

set-option global scrolloff 8,4

set-option global aligntab false
set-option global indentwidth 4

hook global InsertChar '\t' %{ execute-keys -draft "h%opt{indentwidth}@" }
hook global InsertDelete ' ' %{ try %sh{
    printf "%s\n" 'execute-keys -draft -itersel "<a-h><a-k>^\h+.\z<ret>I<space><esc><lt>"'
} catch %{ try %{
    execute-keys -itersel -draft "h%opt{indentwidth}<s-h>2<s-l>s\h+\z<ret>d"
}}}

# TODO: Disable by language. Some are okay.
# set-option global disabled_hooks .*-insert

# ======== maps ========

map global insert <esc> "<esc>;,"
map global normal <esc> ";,"
map global normal <'>   "<a-;>"
map global normal <ret> ":w<ret>"
# TODO: smart comment
map global normal '#'   ":comment-line<ret>"
map global normal  =    ":format-selections<ret>"

map global normal <tab> "<esc>:pick-buffers<ret>"

# Q: it should actually be gw and Gw for consistency
# but I don't think there's a GOTO (goto-extend) mode..? 
map global goto w "<esc>:enter_jump_mode_with_replace_select_mode<ret>" -docstring "jump word"
map global goto W "<esc>:enter_jump_mode_with_extend_select_mode<ret>"  -docstring "jump word"

map global user  t  ":newtab<ret>" -docstring "new tab"
map global user n ":enter-user-mode notes<ret>" -docstring "notes mode"
declare-user-mode notes
map global notes n ":edit ~/notes/daily/%sh{date +%F}.md<ret>" -docstring "daily"
map global notes t ":e ~/notes/todo.md<ret>" -docstring "todos"
