source "%val{config}/plugins/lsp.kak"
source "%val{config}/plugins/buffers.kak"
source "%val{config}/plugins/jump.kak"
# TODO: read through jump

source "%val{config}/utils/clipboard.kak"
source "%val{config}/utils/windowing.kak"
source "%val{config}/utils/notes.kak"
source "%val{config}/utils/sentence.kak"
# TODO: helix inspired match mode

source "%val{config}/filetypes/filetypes.kak"

# ======== appearance ========

colorscheme ashen
set-option global startup_info_version 99999999
set-option global modelinefmt \
    '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}}'
set-option global ui_options terminal_assistant=none
# not a chance... yet?
# set-option global ui_options terminal_info_max_width=1

hook global WinCreate .* %{
    add-highlighter window/ruler column -ruler │ 81 %opt{g_9}
    add-highlighter window/line-numbers number-lines -relative -hlcursor -separator ""
}

# ======== editing ========

hook global InsertCompletionShow .* %{
    map global insert <tab> <c-n>
    map global insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
    unmap global insert <tab>
    unmap global insert <s-tab>
}

set-option global scrolloff 8,4

set-option global aligntab false
set-option global indentwidth 4
set-option global tabstop 4

hook global InsertChar '\t' %{ execute-keys -draft "h%opt{indentwidth}@" }
hook global InsertDelete ' ' %{ try %sh{
    printf "%s\n" 'execute-keys -draft -itersel "<a-h><a-k>^\h+.\z<ret>I<space><esc><lt>"'
} catch %{ try %{
    execute-keys -itersel -draft "h%opt{indentwidth}<s-h>2<s-l>s\h+\z<ret>d"
}}}

# dumb comment
define-command -hidden dumb-comment %{
    try %{ comment-line } catch %{
        execute-keys "x_:comment-block<ret>"
    }
}

# TODO: Disable by language. Some are okay.
# set-option global disabled_hooks .*-insert

# ======== maps ========

map global normal <esc> ";,"
map global normal <'>   "<a-;>"
map global normal '#' ":dumb-comment<ret>"
map global normal  =    ":format-selections<ret>"

map global user  t  ":newtab<ret>" -docstring "new tab"

map global goto n "<esc>:bn<ret>" -docstring "next buffer"
map global goto p "<esc>:bp<ret>" -docstring "previous buffer"

# Q: it should actually be gw and Gw for consistency
# but I don't think there's a GOTO (goto-extend) mode..?
# not without a hook on g/G press updating an option
map global goto w "<esc>:enter_jump_mode_with_replace_select_mode<ret>" -docstring "jump word"
map global goto W "<esc>:enter_jump_mode_with_extend_select_mode<ret>"  -docstring "jump word"
