source "%val{config}/plugins/lsp.kak"
source "%val{config}/plugins/buffers.kak"
# TODO: read through jump
source "%val{config}/plugins/jump.kak"

source "%val{config}/utils/clipboard.kak"
source "%val{config}/utils/windowing.kak"
# TODO: helix inspired match mode

evaluate-commands %sh{
    for file in $kak_config/filetypes/*.kak; do
        printf 'source %s\n' "$file"
    done
}

# ======== appearance ========

colorscheme ashen
set-option global startup_info_version 99999999
set-option -add global modelinefmt \
    '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}}'
set-option global ui_options terminal_assistant=none

hook global WinCreate .* %{
    add-highlighter window/ruler column -ruler │ 81 %opt{g_9}
    add-highlighter window/line-numbers number-lines -relative -hlcursor -separator ""
}

# ======== editing ========

hook global InsertCompletionShow .* %{
    map global insert <tab> <c-n>
    map global insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
    unmap global insert <tab>
    unmap global insert <s-tab>
}

set-option global scrolloff 8,4

set-option global aligntab false
set-option global indentwidth 4
set-option global tabstop 4

hook global InsertChar '\t' %{ execute-keys -draft "h%opt{indentwidth}@" }
hook global InsertDelete ' ' %{ try %sh{
    printf "%s\n" 'execute-keys -draft -itersel "<a-h><a-k>^\h+.\z<ret>I<space><esc><lt>"'
} catch %{ try %{
    execute-keys -itersel -draft "h%opt{indentwidth}<s-h>2<s-l>s\h+\z<ret>d"
}}}

# dumb comment
define-command -hidden dumb-comment %{
    try %{ comment-line } catch %{
        execute-keys "x_:comment-block<ret>"
    }
}

# TODO: Disable by language. Some are okay.
# set-option global disabled_hooks .*-insert

# ======== maps ========

map global normal <esc> ";,"
map global normal <'>   "<a-;>"
map global normal <ret> ":w<ret>"
map global normal '#' ":dumb-comment<ret>"
map global normal  =    ":format-selections<ret>"

map global user  t  ":newtab<ret>" -docstring "new tab"

map global normal <tab> "<esc>:pick-buffers<ret>"

# Q: it should actually be gw and Gw for consistency
# but I don't think there's a GOTO (goto-extend) mode..? 
map global goto w "<esc>:enter_jump_mode_with_replace_select_mode<ret>" -docstring "jump word"
map global goto W "<esc>:enter_jump_mode_with_extend_select_mode<ret>"  -docstring "jump word"

# todo: load daily template if note isn't existing
# use an interactive menu for accessing date tool strings
# maybe integrate with notes too?
declare-user-mode notes
declare-option str notes_dir %sh{echo "$HOME/notes"}
map global user n "<esc>:enter-user-mode notes<ret>" -docstring "notes"
map global notes n ":edit %opt{notes_dir}/daily/%sh{date +%F}.md<ret>" -docstring "daily"
map global notes t ":edit %opt{notes_dir}/todo.md<ret>" -docstring "todo"
map global notes c ":cd %opt{notes_dir}<ret>" -docstring "cd to notes dir"

define-command alacritty-window %{
    nop %sh{
        alacritty msg create-window -e "$(command -v kak)" -c $kak_session
    }
}

