[window]
padding.x = 4
padding.y = 4
option_as_alt = "Both"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[font]
size = 15

[font.normal]
family = "CommitMono"
style = "Regular"

[font.bold]
family = "CommitMono"
style = "Bold"

[font.italic]
family = "CommitMono"
style = "Italic"

[scrolling]
history = 10000

[general]
import = ["~/.config/alacritty/ashen.toml"]
