[window]
dimensions.columns = 90
dimensions.lines = 35
padding.x = 8
padding.y = 8
option_as_alt = "Both"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[font]
size = 25.5
offset.x = 3
offset.y = 8

[font.normal]
family = "CommitMono"
style = "Regular"

[font.bold]
family = "CommitMono"
style = "Bold"

[font.italic]
family = "CommitMono"
style = "Italic"

[scrolling]
history = 10000

[general]
import = ["~/.config/alacritty/ashen.toml"]

[keyboard]
bindings = [
{ key = "[", mods = "Command", action = "SelectPreviousTab" },
{ key = "]", mods = "Command", action = "SelectNextTab",},
{ key = "Enter", mods = "Command", action = "ToggleFullscreen",}
]
