#!/bin/bash

BAT=/sys/class/power_supply/BAT0

while true; do
    now=$(<"$BAT/charge_now")
    cap=$(<"$BAT/charge_full")
    battery=$(( 100 * now / cap))
    status=$(<"$BAT/status")
    charging=''

    if [[ $status == 'Charging' ]]; then
        charging='~'
    elif [[ $status == 'Full' ]]; then
        charging='AC-'
    fi

    date=$(date '+%Y-%m-%d %I:%M')

    echo "${charging}${battery}%, ${date} "
    sleep 5
done
