[language-server.hx-lsp]
command = "hx-lsp"

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "markdown"
language-servers = ["harper-ls", "marksman"]
file-types = ["md", "markdown", "txt"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
soft-wrap.enable = true
text-width = 80

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'<' = '>' # for hugo shortcodes

[[language]]
name = "latex"
indent = { tab-width = 2, unit = "  " }
language-servers = ["texlab", "hx-lsp"]

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
formatter = {command = "clang-format", args = [
  "-style={BasedOnStyle: LLVM, IndentCaseLabels: true, IndentCaseBlocks: true}"
]}
